local Start=dofile('Brainstorm/Advisor/blind_start.lua')
local checks=0
local function eq(a,b,label) checks=checks+1;assert(a==b,label..': '..tostring(a)..' ~= '..tostring(b)) end
local function j(key,id,ability,other)
  local c={key=key,id=id,sell_cost=4,ability=ability or {}}
  for k,v in pairs(other or {}) do c[k]=v end;return c
end
local function state(row)
  return {jokers=row,playing_cards={{id=1,rank=2,suit='Spades',ability={}}},
    hand_size=8,joker_limit=5,hands_left=3,discards_left=4,
    current_round={hands_left=3,discards_left=4},round_resets={hands=3,discards=4},
    probabilities={normal=2},dollars=10,blind={key='bl_small',boss=false}}
end
local dagger=function(id) return j('j_ceremonial',id,{mult=6}) end
local s=state({dagger(1),j('j_joker',2,{mult=4})})
local after,d=Start.project(s)
eq(#after.jokers,1,'victim removed');eq(after.jokers[1].ability.mult,14,'twice sell value')
eq(s.jokers[1].ability.mult,6,'input counter unchanged');eq(#s.jokers,2,'input row unchanged')
eq(after.dollars,10,'destruction is not sale');eq(d.removed[1],2,'victim recorded')
eq(d.stochastic,false,'observed deterministic transition')
after=Start.project(state({dagger(1),j('j_joker',2,{eternal=true})}))
eq(#after.jokers,2,'Eternal protected');eq(after.jokers[1].ability.mult,6,'Eternal no gain')
after=Start.project(state({dagger(1),dagger(2),j('j_joker',3,{})}))
eq(#after.jokers,2,'sliced Dagger cannot slice again');eq(after.jokers[2].id,3,'neighbor behind sliced Dagger stays')
after=Start.project(state({j('j_blueprint',3,{}),dagger(1),j('j_joker',2,{})}))
eq(after.jokers[2].ability.mult,14,'Blueprint does not duplicate Dagger growth')
after=Start.project(state({dagger(1),j('j_oops',2,{},{edition={negative=true}})}))
eq(after.probabilities.normal,1,'destroyed Oops probability');eq(after.joker_limit,4,'destroyed Negative slot')
after=Start.project(state({dagger(1),j('j_troubadour',2,{extra={h_size=2,h_plays=-1}})}))
eq(after.hand_size,6,'Troubadour hand size removed');eq(after.hands_left,3,'Troubadour current hands retained')
eq(after.round_resets.hands,4,'Troubadour future reset')
after=Start.project(state({dagger(1),j('j_stuntman',2,{extra={h_size=2}})}))
eq(after.hand_size,10,'Stuntman removed penalty')
after=Start.project(state({dagger(1),j('j_merry_andy',2,{h_size=-1,d_size=3})}))
eq(after.hand_size,9,'Merry Andy removed hand penalty');eq(after.discards_left,1,'Merry Andy current discards removed')
after=Start.project(state({dagger(1),j('j_oops',2,{},{debuff=true,edition={negative=true}})}))
eq(after.probabilities.normal,2,'debuffed Oops already removed');eq(after.joker_limit,4,'debuffed Negative still removes slot')
after=Start.project(state({dagger(1),j('j_burglar',2,{extra=3})}))
eq(after.hands_left,3,'sliced Burglar no hand gain');eq(after.discards_left,4,'sliced Burglar no discard reset')
after=Start.project(state({j('j_blueprint',1,{}),j('j_burglar',2,{extra=3})}))
eq(after.hands_left,9,'Burglar copied');eq(after.discards_left,0,'Burglar resets discards')
after=Start.project(state({j('j_brainstorm',1,{}),j('j_blueprint',2,{})}))
eq(after.hands_left,3,'copy cycle bounded')
after=Start.project(state({j('j_marble',1,{}),j('j_hologram',2,{x_mult=2,extra=.25})}),{sample_index=2})
eq(#after.playing_cards,2,'Marble adds one');eq(after.playing_cards[2].enhancement,'m_stone','Stone enhancement')
eq(after.playing_cards[2].ability.bonus,50,'Stone source chips');eq(after.jokers[2].ability.x_mult,2.25,'Marble Hologram gain')
local a,b=Start.project(state({j('j_blueprint',1,{}),j('j_marble',2,{})}),{sample_index=3})
eq(#a.playing_cards,3,'copied Marble adds two');eq(b.stochastic,true,'Marble sampling explicit')
eq(#b.generated,2,'both added cards recorded')
local again=Start.project(state({j('j_blueprint',1,{}),j('j_marble',2,{})}),{sample_index=3})
eq(a.playing_cards[2].rank,again.playing_cards[2].rank,'deterministic front rank')
eq(a.playing_cards[2].suit,again.playing_cards[2].suit,'deterministic front suit')
after=Start.project(state({dagger(1),j('j_marble',2,{})}))
eq(#after.playing_cards,1,'sliced Marble does not generate')
after=Start.project(state({dagger(1),j('j_blueprint',2,{}),j('j_marble',3,{})}))
eq(#after.playing_cards,2,'sliced copy origin cannot generate a second Stone')
after=Start.project(state({dagger(1),j('j_blueprint',2,{}),j('j_burglar',3,{extra=3})}))
eq(after.hands_left,6,'sliced copy origin cannot duplicate Burglar')
after=Start.project(state({j('j_marble',1,{}),dagger(2),j('j_hologram',3,{x_mult=2,extra=.25})}))
eq(#after.jokers,2,'Hologram can grow then be destroyed');eq(after.jokers[2].ability.mult,14,'destruction sees sell value not XMult')
after=Start.project(state({dagger(1),j('j_hologram',2,{x_mult=2,extra=.25}),j('j_marble',3,{})}))
eq(#after.playing_cards,2,'later Marble still creates')
local unknown,reason=Start.project(state({dagger(1),j('j_joker',2,{},{sell_cost=false})}))
eq(unknown,nil,'unknown resale fails closed');eq(type(reason),'string','unknown reason')
eq(Start.project(state({j('j_madness',1,{extra=.5,x_mult=1})})),nil,'unsupported random destruction')
local boss=state({dagger(1),j('j_joker',2,{}),j('j_chicot',3,{})});boss.blind={key='mod_boss',boss=true}
eq(Start.project(boss),nil,'unknown Chicot boss disable remains unsupported')
eq(Start.project(state({j('j_marble',1,{})}),{sample_index=5}),nil,'sample bound')
eq(Start.supports(j('j_marble',1,{})),true,'supported API')
eq(Start.supports(j('j_madness',1,{})),false,'unsupported API')
print('advisor blind start tests: '..checks..' checks passed')
