--- STEAMODDED HEADER
--- MOD_NAME: Brainstorm-Rerolled
--- MOD_ID: Brainstorm-Rerolled
--- PREFIX: brainstorm
--- MOD_AUTHOR: [ABGamma]
--- MOD_DESCRIPTION: Automatic seed searching with configurable cards, Jokers, packs, tags, and vouchers.
--- VERSION: 2.10.0-alpha
